name: deploy
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    env:
      VITE_API_BASE: 'https://todo-app.centralindia.cloudapp.azure.com/api/v1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-
      - name: Install dependencies
        run: npm install --dev
      - run: |
          npm run build
          cp -rv dist/* /var/www/todo-app.centralindia.cloudapp.azure.com/
